---

- name: Add MongoDB to image
  hosts: all
  become: true
  tasks:
    - name: Add apt key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-3.2.asc
        state: present
    - name: Add Mongo repo to source list
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present
    - name: Update apt cache & install mongo
      apt:
        name: mongodb-org
        update_cache: yes
    - name: Enabling service
      systemd:
        name: mongod
        enabled: yes
