#cloud-config
users:
  - name: yc-user
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC1yedF5YHYr+3MmBzHuqqcov1JTYJW1/bzruEwn5AEuP6ehctATubkMkhQejBM/MLnRuY80lhtIMdkymKIUR4+1yFoMaT9NpIPwSCMYgFiPnyEJkr3usZt9l7rgRPFVdnEqybWqBr+OZkj/tA1BVv8gB308cOFpT7uhCD7vpThke4WY5I0eSJU5BQeoPxWh5gpaZ5vXRcrnfMZK8IIeiwwW5pt9/B/qjaoaSM4vMS0E1qyM7jLaq2jhnvwfb0ijOcOBTUXzrGuip0QAJAK9f6/vgAf5H5tq6Cn80fdM+yY1gghH4nRrqWi0sD5nxYOi2NNp2tqw+XbstTz9lmpWkOIgWIAl8vivS+sQhuphvk/V8hhxgDwxnBSY0xqOwUOJtHP7uqQzPI8WyccG0NYHi/VMJ+vH1AnQBSMW/bdzoHmQJHIFYFpGTOcqu1dNy4ZKacAl5R79gBwOV1twosC/D61P9pVPAZJG+GafJVyCUMd2RNQZu0HF9fQQzFXQtznUoc= appuser

runcmd:
  - 'wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -'
  - 'echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list'
  - 'sudo apt update'
  - 'sudo apt install -y ruby-full ruby-bundler build-essential mongodb-org git'
  - 'sudo systemctl start mongod'
  - 'sudo systemctl enable mongod'
  - 'git clone -b monolith https://github.com/express42/reddit.git'
  - 'cd reddit && bundle install'
  - 'puma -d'
