---
- name: Deploy App
  hosts: app
  become: true
  tasks:
    - name: Install Git
      apt:
        name: git
        state: present

    - name: Get the latest app source
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith
      notify: restart puma

    - name: Bundle Install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit

  handlers:
  - name: restart puma
    become: true
    systemd: name=puma state=restarted
